---
branches:
  only:
    - master
language: ruby
before_install: 'bundle install'
bundler_args: --without development
script: 'bundle exec rake spec'
rvm:
  - 2.0.0
gemfile: Gemfile
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.6.0" BEAKER_VERSION="2.50.0"
    - PUPPET_GEM_VERSION="~> 3.7.1" BEAKER_VERSION="2.50.0"
    - PUPPET_GEM_VERSION="~> 4.0.0" BEAKER_VERSION="2.50.0"
    - PUPPET_GEM_VERSION="~> 4.5.0" BEAKER_VERSION="2.50.0"

